apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-predictor
  labels:
    app: diabetes-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-predictor
  template:
    metadata:
      labels:
        app: diabetes-predictor
    spec:
      containers:
        - name: diabetes-api
          image: your-dockerhub-username/mlops-diabetes-predictor:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-predictor-service
spec:
  selector:
    app: diabetes-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer